Add intial support for using JS9 on the Desktop   -- the js9 script has a -b switch that will start a browser ...   -- ... and load the image specified on the command line   -- supports chrome, firefox, safari browsers

diff --git a/js9.in b/js9.in
--- a/js9.in
+++ b/js9.in
@@ -1,43 +1,54 @@
-#!/bin/sh
-# set -x
+#!/bin/bash
+#set -x
 
-# default will be filled in by mkjs9
-JTYPE=""
-JPORT=""
-WEBDIR=""
-
-# sanity check: type must be nodejs
-if [ x"$JTYPE" != xnodejs ]; then
-    echo "JS9 helper type must be 'nodejs' for messaging (not '$JTYPE')"
-    exit 1
+# values will be filled in by mkjs9
+if [ x${JS9_SRCDIR} = x ]; then
+  JS9_SRCDIR=""
+fi
+if [ x${JS9_INSTALLDIR} = x ]; then
+  JS9_INSTALLDIR=""
 fi
 
-# add webdir to module path
-if [ x${JS9_NODE_PATH} != x ]; then
-  NODE_PATH="${JS9_NODE_PATH}"
-else
-  # look in current directory first
-  if [ -r ./js9Msg.js -a -d ./node_modules ]; then
-    NODE_PATH="."
-  else
-    NODE_PATH="${WEBDIR:-.}"
-  fi
+# make sure js9Msg sees these, if possible
+if [ x${JS9_SRCDIR} != x ]; then
+  export JS9_SRCDIR
+fi
+if [ x${JS9_INSTALLDIR} != x ]; then
+  export JS9_INSTALLDIR
+fi
+
+# error routine
+error () {
+  echo "ERROR: $*" >&2
+  exit 1
+}
+
+# sanity check: node must be present
+hash node 1>/dev/null 2>&1
+if [ $? != 0 ]; then
+  error "JS9 messaging requires Node.js (see: https://nodejs.org/)"
+fi
+
+# add to node module path (is this still necessary?)
+if [ -d ./node_modules ]; then
+  NODE_PATH="./node_modules:${NODE_PATH}"
+elif [ -d ${JS9_INSTALLDIR}/node_modules ]; then
+  NODE_PATH="${JS9_INSTALLDIR}/node_modules:${NODE_PATH}"
+elif [ -d ${JS9_SRCDIR}/node_modules ]; then
+  NODE_PATH="${JS9_SRCDIR}/node_modules:${NODE_PATH}"
 fi
 export NODE_PATH
 
-# set up helper port, if possible
-if [ x"$JPORT" != x ]; then
-  export JS9_HELPER_PORT="$JPORT"
-fi
-
-# make sure we're set up correctly
-if [ ! -r ${NODE_PATH}/js9Msg.js ]; then
-  echo "ERROR: can't find js9Msg.js in '$NODE_PATH'"
-  exit 1
-elif [ ! -d ${NODE_PATH}/node_modules ]; then
-  echo "ERROR: can't find node_modules directory in '$NODE_PATH'"
-  exit 2
+# make sure we can find the JS9 messaging script
+if [ -r ./js9Msg.js ]; then
+  JS9_MSGSCRIPT="./js9Msg.js"
+elif [ -r ${JS9_INSTALLDIR}/js9Msg.js ]; then
+  JS9_MSGSCRIPT="${JS9_INSTALLDIR}/js9Msg.js"
+elif [ -r ${JS9_SRCDIR}/js9Msg.js ]; then
+  JS9_MSGSCRIPT="${JS9_SRCDIR}/js9Msg.js"
+else
+  error "ERROR: can't find js9Msg.js script (install JS9, or set \$JS9_SRCDIR )"
 fi
 
 # run node with the msg script
-exec node $NODE_PATH/js9Msg.js $*
+exec node $JS9_MSGSCRIPT $*
