handle spaces in args when exec'ing js9msg (#2)

diff --git a/build/js9.in b/build/js9.in
--- a/build/js9.in
+++ b/build/js9.in
@@ -49,7 +49,7 @@ OS=`uname -s`
 
 # error routine
 error () {
-  echo "ERROR: $*" >&2
+  echo "ERROR: $@" >&2
   exit 1
 }
 
@@ -195,9 +195,9 @@ if [ x"$JS9_TO_JS9MSG" != xfalse ]; then
     command -v wget curl 1>/dev/null 2>&1
     if [ $? = 0 ]; then
       if [ x$DOVERIFY = xtrue ]; then
-        echo "exec'ing: js9msg $*"
+        echo "exec'ing: js9msg $@"
       fi
-      exec js9msg $*
+      exec js9msg "$@"
     fi
   fi
 fi
@@ -280,7 +280,7 @@ export JS9_BROWSER
 
 # run node or Electron with the msg script
 if [ x$DOVERIFY = xtrue ]; then
-  echo "executing: $JS9_XEQ" "$JS9_MSGSCRIPT" $*
+  echo "executing: $JS9_XEQ" "$JS9_MSGSCRIPT" $@
 fi
 
 # we need to quote the remaining arguments to deal with spaces in filenames
