a miscellany:   -- prevent building with cfitsio 3.44, which breaks JS9   -- js9Xeq: sanity check ensures that system tools (awk, grep) are available   -- document need for system tools to be in js9 helper's PATH

diff --git a/analysis-wrappers/js9Xeq b/analysis-wrappers/js9Xeq
--- a/analysis-wrappers/js9Xeq
+++ b/analysis-wrappers/js9Xeq
@@ -56,6 +56,12 @@ quotacheck () {
   fi
 }
 
+# sanity check that we have system programs in the path
+hash awk sed egrep du mv rm cat echo 1>/dev/null 2>&1
+if [ $? != 0 ]; then
+      error "can't find system programs (e.g. awk, sed). Please check the PATH of the JS9 helper."
+fi
+
 # regcnts is preferred
 hash regcnts 1>/dev/null 2>&1
 if [ $? = 0 ]; then
